123321      (do not change this line and the order of the following lines!)
 1          (1=model fitting, 2=importance ranking, 3=data conversion)
"../../../output/joos/guide_output.txt"  (name of output file)
 1          (1=one tree, 2=ensemble)
 2          (1=classification, 2=regression)
 1          (1=linear, 2=quantile, 3=Poisson, 4=hazard, 5=longitudinal/multiresponse)
 1          (1=least squares, 2=least median of squares)
 1          (0=stepwise, 1=multiple, 2=polynomial, 3=constant, 4=ANCOVA)
    1       (1=intercept, 2=no intercept)
    0       (truncation: 0=none, 1=node range, 2=+10% node range, 3=global range, 4=Windsorization)
 1          (1=interaction tests, 2=skip them)
 1          (1=prune by CV, 2=no pruning)
"./linear.txt"  (name of data description file)
 1          (1 to use default number of cross-validations, 2 to change it)
 1          (Tree selection method)
    0.5     (SE number for pruning)
 2          (1=split point from quantiles, 2=use exhaustive search)
 1          (1=use default max split levels, 2=change it)
 1          (1=use default mindat, 2=change it)
 2          (1=skip latex, 2=write latex)
"../../../output/joos/tree.tex" (latex file name)
 1          (1=vertical tree, 2=sideways tree)
 1          (1=include node numbers, 2=exclude)
 2          (1=number all nodes, 2=only leaf nodes)
 6          (choice of colors: 1-11)
 3          (1=no storage, 2=store fit and split variables, 3=store split variables and values)
"../../../output/joos/splits.txt" (split variable file name)
 2          (1=do not save regression coefs, 2=save them)
"../../../output/joos/coefs.txt" (regression coefficients file name)
 1          (1=do not save predicted values, 2=save them)
 1          (1=do not save terminal nodes, 2=save them  [for importance scoring])