123321      (do not change this line and the order of the following lines!)
 2          (1=model fitting, 2=importance ranking, 3=data conversion)
"../../../output/joos/guided_selection.txt"  (name of output file)
 1          (1=classification, 2=regression)
 1          (1=linear+interaction tests, 2=skip linear, 3=skip both)
"./selection.txt"  (name of data description file)
 1          (1=accept default expected # erroneous noise variables, 2=change)
 2          (1=estimated priors, 2=equal priors, 3=other priors)
 1          (1=unit misclassification costs, 2=other)
 2          (1=split point from quantiles, 2=use exhaustive search)
 1          (1=no info on split levels, min. node size, and node IDs, 2=yes)
 1          (1=use default max split levels, 2=change it)
 2          (1=use default mindat, 2=change it)
        8   (min. node size)
 1          (1=do not create description file for selected variables, 2=create the file)
 2          (1=do not create, 2=create file for importance scores)
"../../../output/joos/selection.txt" (file name for importance scores)
