123321      (do not change this line and the order of the following lines!)
 1          (1=model fitting, 2=importance ranking, 3=data conversion)
"../../../output/otter/major.txt"  (name of output file)
 1          (1=one tree, 2=ensemble)
 1          (1=classification, 2=regression)
 1          (1=simple model, 2=nearest-neighbor, 3=kernel)
 3          (1=linear+interaction tests, 2=skip linear, 3=skip both)
 1          (1=prune by CV, 2=by test sample, 3=no pruning)
"./major.txt"  (name of data description file)
 1          (1 to use default number of cross-validations, 2 to change it)
 1          (1=mean-based CV tree, 2=median-based CV tree)
    0.50    (SE number for pruning)
 1          (1=estimated priors, 2=equal priors, 3=other priors)
 1          (1=unit misclassification costs, 2=other)
 2          (1=split point from quantiles, 2=use exhaustive search)
 1          (1=use default max split levels, 2=change it)
 1          (1=use default mindat, 2=change it)
 2          (1=skip latex, 2=write latex)
"../../../output/otter/major.tex" (latex file name)
 1          (1=vertical tree, 2=sideways tree)
 1          (1=include node numbers, 2=exclude)
 2          (1=number all nodes, 2=only leaf nodes)
 1          (1=color leaf nodes, 2=no colors)
 1          (1=no storage, 2=store fit and split variables, 3=store split variables and values)
 1          (1=do not save node IDs in separate file, 2=save them)
 1          (1=do not save terminal node IDs in a file, 2=save them)