123321      (do not change this line and the order of the following lines!)
 1          (1=model fitting, 2=importance ranking, 3=data conversion)
"temp_out.txt"  (name of output file)
 1          (1=one tree, 2=ensemble)
 2          (1=classification, 2=regression)
 1          (1=linear, 2=quantile, 3=Poisson, 4=hazard, 5=multiresponse or longitudinal without T, 6=longitudinal with T)
 1          (1=least squares, 2=least median of squares)
 0          (0=stepwise, 1=multiple, 2=polynomial, 3=constant, 4=ANCOVA)
 1          (1=forward+backward, 2=forward, 3=all subsets)
     0      (max number of variables to be selected; 0=max possible)
  4.00      (f-to-enter)
  3.99      (f-to-delete)
 0          (0=none, 1=node range, 2=+10% node range, 3=global range, 4=2-sided Winsorization)
 1          (1=interaction tests, 2=skip them)
 1          (1=prune by CV, 2=no pruning)
"eagle/no_snow.txt"  (name of data description file)
 1          (1 to use default number of cross-validations, 2 to change it)
 1          (1=mean-based CV tree, 2=median-based CV tree)
    0.50    (SE number for pruning)
 1          (1=accept default splitting fraction, 2=change it)
 1          (1=use default max split levels, 2=change it)
 1          (1=use default mindat, 2=change it)
 1          (1=skip latex, 2=write latex)
 1          (1=no storage, 2=store fit and split variables, 3=store split variables and values)
 1          (1=do not save, 2=save regression coefs in separate file)
 1          (1=do not save node IDs in separate file, 2=save them)
 1          (1=do not save terminal node IDs in a file, 2=save them)
